ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:3857").setExtent([9627857.725103, -2007607.356965, 16589752.146140, 2310881.908203]);
var wms_layers = [];


        var lyr_GoogleMaps_0 = new ol.layer.Tile({
            'title': 'Google Maps',
            //'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}'
            })
        });

        var lyr_OpenStreetMap_1 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            //'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_IndeksPetaRBISkala125K_2 = new ol.format.GeoJSON();
var features_IndeksPetaRBISkala125K_2 = format_IndeksPetaRBISkala125K_2.readFeatures(json_IndeksPetaRBISkala125K_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_IndeksPetaRBISkala125K_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_IndeksPetaRBISkala125K_2.addFeatures(features_IndeksPetaRBISkala125K_2);
var lyr_IndeksPetaRBISkala125K_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_IndeksPetaRBISkala125K_2, 
                style: style_IndeksPetaRBISkala125K_2,
                popuplayertitle: "Indeks Peta RBI Skala 1:25K",
                interactive: true,
                    title: '<img src="styles/legend/IndeksPetaRBISkala125K_2.png" /> Indeks Peta RBI Skala 1:25K'
                });
var format_IndeksPetaRBISkala150K_3 = new ol.format.GeoJSON();
var features_IndeksPetaRBISkala150K_3 = format_IndeksPetaRBISkala150K_3.readFeatures(json_IndeksPetaRBISkala150K_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_IndeksPetaRBISkala150K_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_IndeksPetaRBISkala150K_3.addFeatures(features_IndeksPetaRBISkala150K_3);
var lyr_IndeksPetaRBISkala150K_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_IndeksPetaRBISkala150K_3, 
                style: style_IndeksPetaRBISkala150K_3,
                popuplayertitle: "Indeks Peta RBI Skala 1:50K",
                interactive: true,
                    title: '<img src="styles/legend/IndeksPetaRBISkala150K_3.png" /> Indeks Peta RBI Skala 1:50K'
                });

lyr_GoogleMaps_0.setVisible(true);lyr_OpenStreetMap_1.setVisible(true);lyr_IndeksPetaRBISkala125K_2.setVisible(true);lyr_IndeksPetaRBISkala150K_3.setVisible(true);
var layersList = [lyr_GoogleMaps_0,lyr_OpenStreetMap_1,lyr_IndeksPetaRBISkala125K_2,lyr_IndeksPetaRBISkala150K_3];
lyr_IndeksPetaRBISkala125K_2.set('fieldAliases', {'OBJECTID_1': 'OBJECTID_1', 'OBJECTID': 'OBJECTID', 'Id': 'Id', 'REGION': 'REGION', 'NOMOR_PETA': 'NOMOR_PETA', 'NAMA_PETA': 'NAMA_PETA', 'SKALA_PETA': 'SKALA_PETA', 'ZONE_UTM': 'ZONE_UTM', 'TLM_DIG': 'TLM_DIG', 'TLM_SEAM': 'TLM_SEAM', 'DTM': 'DTM', 'QLOOK': 'QLOOK', 'METADATA': 'METADATA', 'GAZ': 'GAZ', 'THN_BUAT1': 'THN_BUAT1', 'SBR_DATA1': 'SBR_DATA1', 'METODE1': 'METODE1', 'TLM_SEAM1': 'TLM_SEAM1', 'DTM1': 'DTM1', 'QLOOK1': 'QLOOK1', 'METADATA1': 'METADATA1', 'GAZ1': 'GAZ1', 'NAMA_PEK1': 'NAMA_PEK1', 'PELAKSANA1': 'PELAKSANA1', 'THN_BUAT2': 'THN_BUAT2', 'SBR_DATA2': 'SBR_DATA2', 'METODE2': 'METODE2', 'TLM_SEAM2': 'TLM_SEAM2', 'DTM2': 'DTM2', 'QLOOK2': 'QLOOK2', 'METADATA2': 'METADATA2', 'GAZ2': 'GAZ2', 'NAMA_PEK2': 'NAMA_PEK2', 'PELAKSANA2': 'PELAKSANA2', 'THN_BUAT3': 'THN_BUAT3', 'SBR_DATA3': 'SBR_DATA3', 'METODE3': 'METODE3', 'TLM_SEAM3': 'TLM_SEAM3', 'DTM3': 'DTM3', 'QLOOK3': 'QLOOK3', 'METADATA3': 'METADATA3', 'GAZ3': 'GAZ3', 'NAMA_PEK3': 'NAMA_PEK3', 'PELAKSANA3': 'PELAKSANA3', 'THN_BUAT4': 'THN_BUAT4', 'SBR_DATA4': 'SBR_DATA4', 'METODE4': 'METODE4', 'TLM_SEAM4': 'TLM_SEAM4', 'DTM4': 'DTM4', 'QLOOK4': 'QLOOK4', 'METADATA4': 'METADATA4', 'GAZ4': 'GAZ4', 'NAMA_PEK4': 'NAMA_PEK4', 'PELAKSANA4': 'PELAKSANA4', 'THN_BUAT5': 'THN_BUAT5', 'SBR_DATA5': 'SBR_DATA5', 'METODE5': 'METODE5', 'TLM_SEAM5': 'TLM_SEAM5', 'DTM5': 'DTM5', 'QLOOK5': 'QLOOK5', 'METADATA5': 'METADATA5', 'GAZ5': 'GAZ5', 'NAMA_PEK5': 'NAMA_PEK5', 'PELAKSANA5': 'PELAKSANA5', 'THN_BUAT': 'THN_BUAT', 'SBR_DATA': 'SBR_DATA', 'METODE': 'METODE', 'NAMA_PEK': 'NAMA_PEK', 'PELAKSANA': 'PELAKSANA', 'THN_SEAM': 'THN_SEAM', 'THN_DTM': 'THN_DTM', 'THN_QLOOK': 'THN_QLOOK', 'THN_META': 'THN_META', 'THN_GAZ': 'THN_GAZ', 'KET': 'KET', 'SHAPE_Leng': 'SHAPE_Leng', 'Shape_Le_1': 'Shape_Le_1', 'Shape_Le_2': 'Shape_Le_2', 'Shape_Le_3': 'Shape_Le_3', 'Shape_Area': 'Shape_Area', });
lyr_IndeksPetaRBISkala150K_3.set('fieldAliases', {'Id': 'Id', 'REGION': 'REGION', 'NOMOR_PETA': 'NOMOR_PETA', 'NAMA_PETA': 'NAMA_PETA', 'SKALA_PETA': 'SKALA_PETA', 'ZONE_UTM': 'ZONE_UTM', 'TLM_DIG': 'TLM_DIG', 'TLM_SEAM': 'TLM_SEAM', 'DTM': 'DTM', 'QLOOK': 'QLOOK', 'METADATA': 'METADATA', 'GAZ': 'GAZ', 'THN_BUAT1': 'THN_BUAT1', 'SBR_DATA1': 'SBR_DATA1', 'METODE1': 'METODE1', 'TLM_SEAM1': 'TLM_SEAM1', 'DTM1': 'DTM1', 'QLOOK1': 'QLOOK1', 'METADATA1': 'METADATA1', 'GAZ1': 'GAZ1', 'NAMA_PEK1': 'NAMA_PEK1', 'PELAKSANA1': 'PELAKSANA1', 'THN_BUAT2': 'THN_BUAT2', 'SBR_DATA2': 'SBR_DATA2', 'METODE2': 'METODE2', 'TLM_SEAM2': 'TLM_SEAM2', 'DTM2': 'DTM2', 'QLOOK2': 'QLOOK2', 'METADATA2': 'METADATA2', 'GAZ2': 'GAZ2', 'NAMA_PEK2': 'NAMA_PEK2', 'PELAKSANA2': 'PELAKSANA2', 'THN_BUAT3': 'THN_BUAT3', 'SBR_DATA3': 'SBR_DATA3', 'METODE3': 'METODE3', 'TLM_SEAM3': 'TLM_SEAM3', 'DTM3': 'DTM3', 'QLOOK3': 'QLOOK3', 'METADATA3': 'METADATA3', 'GAZ3': 'GAZ3', 'NAMA_PEK3': 'NAMA_PEK3', 'PELAKSANA3': 'PELAKSANA3', 'THN_BUAT4': 'THN_BUAT4', 'SBR_DATA4': 'SBR_DATA4', 'METODE4': 'METODE4', 'TLM_SEAM4': 'TLM_SEAM4', 'DTM4': 'DTM4', 'QLOOK4': 'QLOOK4', 'METADATA4': 'METADATA4', 'GAZ4': 'GAZ4', 'NAMA_PEK4': 'NAMA_PEK4', 'PELAKSANA4': 'PELAKSANA4', 'THN_BUAT5': 'THN_BUAT5', 'SBR_DATA5': 'SBR_DATA5', 'METODE5': 'METODE5', 'TLM_SEAM5': 'TLM_SEAM5', 'DTM5': 'DTM5', 'QLOOK5': 'QLOOK5', 'METADATA5': 'METADATA5', 'GAZ5': 'GAZ5', 'NAMA_PEK5': 'NAMA_PEK5', 'PELAKSANA5': 'PELAKSANA5', 'THN_BUAT': 'THN_BUAT', 'SBR_DATA': 'SBR_DATA', 'METODE': 'METODE', 'NAMA_PEK': 'NAMA_PEK', 'PELAKSANA': 'PELAKSANA', 'THN_SEAM': 'THN_SEAM', 'THN_DTM': 'THN_DTM', 'THN_QLOOK': 'THN_QLOOK', 'THN_META': 'THN_META', 'THN_GAZ': 'THN_GAZ', 'KET': 'KET', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', });
lyr_IndeksPetaRBISkala125K_2.set('fieldImages', {'OBJECTID_1': 'TextEdit', 'OBJECTID': 'TextEdit', 'Id': 'TextEdit', 'REGION': 'TextEdit', 'NOMOR_PETA': 'TextEdit', 'NAMA_PETA': 'TextEdit', 'SKALA_PETA': 'TextEdit', 'ZONE_UTM': 'TextEdit', 'TLM_DIG': 'TextEdit', 'TLM_SEAM': 'TextEdit', 'DTM': 'TextEdit', 'QLOOK': 'TextEdit', 'METADATA': 'TextEdit', 'GAZ': 'TextEdit', 'THN_BUAT1': 'TextEdit', 'SBR_DATA1': 'TextEdit', 'METODE1': 'TextEdit', 'TLM_SEAM1': 'TextEdit', 'DTM1': 'TextEdit', 'QLOOK1': 'TextEdit', 'METADATA1': 'TextEdit', 'GAZ1': 'TextEdit', 'NAMA_PEK1': 'TextEdit', 'PELAKSANA1': 'TextEdit', 'THN_BUAT2': 'TextEdit', 'SBR_DATA2': 'TextEdit', 'METODE2': 'TextEdit', 'TLM_SEAM2': 'TextEdit', 'DTM2': 'TextEdit', 'QLOOK2': 'TextEdit', 'METADATA2': 'TextEdit', 'GAZ2': 'TextEdit', 'NAMA_PEK2': 'TextEdit', 'PELAKSANA2': 'TextEdit', 'THN_BUAT3': 'TextEdit', 'SBR_DATA3': 'TextEdit', 'METODE3': 'TextEdit', 'TLM_SEAM3': 'TextEdit', 'DTM3': 'TextEdit', 'QLOOK3': 'TextEdit', 'METADATA3': 'TextEdit', 'GAZ3': 'TextEdit', 'NAMA_PEK3': 'TextEdit', 'PELAKSANA3': 'TextEdit', 'THN_BUAT4': 'TextEdit', 'SBR_DATA4': 'TextEdit', 'METODE4': 'TextEdit', 'TLM_SEAM4': 'TextEdit', 'DTM4': 'TextEdit', 'QLOOK4': 'TextEdit', 'METADATA4': 'TextEdit', 'GAZ4': 'TextEdit', 'NAMA_PEK4': 'TextEdit', 'PELAKSANA4': 'TextEdit', 'THN_BUAT5': 'TextEdit', 'SBR_DATA5': 'TextEdit', 'METODE5': 'TextEdit', 'TLM_SEAM5': 'TextEdit', 'DTM5': 'TextEdit', 'QLOOK5': 'TextEdit', 'METADATA5': 'TextEdit', 'GAZ5': 'TextEdit', 'NAMA_PEK5': 'TextEdit', 'PELAKSANA5': 'TextEdit', 'THN_BUAT': 'TextEdit', 'SBR_DATA': 'TextEdit', 'METODE': 'TextEdit', 'NAMA_PEK': 'TextEdit', 'PELAKSANA': 'TextEdit', 'THN_SEAM': 'TextEdit', 'THN_DTM': 'TextEdit', 'THN_QLOOK': 'TextEdit', 'THN_META': 'TextEdit', 'THN_GAZ': 'TextEdit', 'KET': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'Shape_Le_1': 'TextEdit', 'Shape_Le_2': 'TextEdit', 'Shape_Le_3': 'TextEdit', 'Shape_Area': 'TextEdit', });
lyr_IndeksPetaRBISkala150K_3.set('fieldImages', {'Id': 'Range', 'REGION': 'TextEdit', 'NOMOR_PETA': 'TextEdit', 'NAMA_PETA': 'TextEdit', 'SKALA_PETA': 'TextEdit', 'ZONE_UTM': 'TextEdit', 'TLM_DIG': 'TextEdit', 'TLM_SEAM': 'TextEdit', 'DTM': 'TextEdit', 'QLOOK': 'TextEdit', 'METADATA': 'TextEdit', 'GAZ': 'TextEdit', 'THN_BUAT1': 'TextEdit', 'SBR_DATA1': 'TextEdit', 'METODE1': 'TextEdit', 'TLM_SEAM1': 'TextEdit', 'DTM1': 'TextEdit', 'QLOOK1': 'TextEdit', 'METADATA1': 'TextEdit', 'GAZ1': 'TextEdit', 'NAMA_PEK1': 'TextEdit', 'PELAKSANA1': 'TextEdit', 'THN_BUAT2': 'TextEdit', 'SBR_DATA2': 'TextEdit', 'METODE2': 'TextEdit', 'TLM_SEAM2': 'TextEdit', 'DTM2': 'TextEdit', 'QLOOK2': 'TextEdit', 'METADATA2': 'TextEdit', 'GAZ2': 'TextEdit', 'NAMA_PEK2': 'TextEdit', 'PELAKSANA2': 'TextEdit', 'THN_BUAT3': 'TextEdit', 'SBR_DATA3': 'TextEdit', 'METODE3': 'TextEdit', 'TLM_SEAM3': 'TextEdit', 'DTM3': 'TextEdit', 'QLOOK3': 'TextEdit', 'METADATA3': 'TextEdit', 'GAZ3': 'TextEdit', 'NAMA_PEK3': 'TextEdit', 'PELAKSANA3': 'TextEdit', 'THN_BUAT4': 'TextEdit', 'SBR_DATA4': 'TextEdit', 'METODE4': 'TextEdit', 'TLM_SEAM4': 'TextEdit', 'DTM4': 'TextEdit', 'QLOOK4': 'TextEdit', 'METADATA4': 'TextEdit', 'GAZ4': 'TextEdit', 'NAMA_PEK4': 'TextEdit', 'PELAKSANA4': 'TextEdit', 'THN_BUAT5': 'TextEdit', 'SBR_DATA5': 'TextEdit', 'METODE5': 'TextEdit', 'TLM_SEAM5': 'TextEdit', 'DTM5': 'TextEdit', 'QLOOK5': 'TextEdit', 'METADATA5': 'TextEdit', 'GAZ5': 'TextEdit', 'NAMA_PEK5': 'TextEdit', 'PELAKSANA5': 'TextEdit', 'THN_BUAT': 'TextEdit', 'SBR_DATA': 'TextEdit', 'METODE': 'TextEdit', 'NAMA_PEK': 'TextEdit', 'PELAKSANA': 'TextEdit', 'THN_SEAM': 'TextEdit', 'THN_DTM': 'TextEdit', 'THN_QLOOK': 'TextEdit', 'THN_META': 'TextEdit', 'THN_GAZ': 'TextEdit', 'KET': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', });
lyr_IndeksPetaRBISkala125K_2.set('fieldLabels', {'OBJECTID_1': 'no label', 'OBJECTID': 'no label', 'Id': 'no label', 'REGION': 'no label', 'NOMOR_PETA': 'no label', 'NAMA_PETA': 'no label', 'SKALA_PETA': 'no label', 'ZONE_UTM': 'no label', 'TLM_DIG': 'no label', 'TLM_SEAM': 'no label', 'DTM': 'no label', 'QLOOK': 'no label', 'METADATA': 'no label', 'GAZ': 'no label', 'THN_BUAT1': 'no label', 'SBR_DATA1': 'no label', 'METODE1': 'no label', 'TLM_SEAM1': 'no label', 'DTM1': 'no label', 'QLOOK1': 'no label', 'METADATA1': 'no label', 'GAZ1': 'no label', 'NAMA_PEK1': 'no label', 'PELAKSANA1': 'no label', 'THN_BUAT2': 'no label', 'SBR_DATA2': 'no label', 'METODE2': 'no label', 'TLM_SEAM2': 'no label', 'DTM2': 'no label', 'QLOOK2': 'no label', 'METADATA2': 'no label', 'GAZ2': 'no label', 'NAMA_PEK2': 'no label', 'PELAKSANA2': 'no label', 'THN_BUAT3': 'no label', 'SBR_DATA3': 'no label', 'METODE3': 'no label', 'TLM_SEAM3': 'no label', 'DTM3': 'no label', 'QLOOK3': 'no label', 'METADATA3': 'no label', 'GAZ3': 'no label', 'NAMA_PEK3': 'no label', 'PELAKSANA3': 'no label', 'THN_BUAT4': 'no label', 'SBR_DATA4': 'no label', 'METODE4': 'no label', 'TLM_SEAM4': 'no label', 'DTM4': 'no label', 'QLOOK4': 'no label', 'METADATA4': 'no label', 'GAZ4': 'no label', 'NAMA_PEK4': 'no label', 'PELAKSANA4': 'no label', 'THN_BUAT5': 'no label', 'SBR_DATA5': 'no label', 'METODE5': 'no label', 'TLM_SEAM5': 'no label', 'DTM5': 'no label', 'QLOOK5': 'no label', 'METADATA5': 'no label', 'GAZ5': 'no label', 'NAMA_PEK5': 'no label', 'PELAKSANA5': 'no label', 'THN_BUAT': 'no label', 'SBR_DATA': 'no label', 'METODE': 'no label', 'NAMA_PEK': 'no label', 'PELAKSANA': 'no label', 'THN_SEAM': 'no label', 'THN_DTM': 'no label', 'THN_QLOOK': 'no label', 'THN_META': 'no label', 'THN_GAZ': 'no label', 'KET': 'no label', 'SHAPE_Leng': 'no label', 'Shape_Le_1': 'no label', 'Shape_Le_2': 'no label', 'Shape_Le_3': 'no label', 'Shape_Area': 'no label', });
lyr_IndeksPetaRBISkala150K_3.set('fieldLabels', {'Id': 'no label', 'REGION': 'no label', 'NOMOR_PETA': 'no label', 'NAMA_PETA': 'no label', 'SKALA_PETA': 'no label', 'ZONE_UTM': 'no label', 'TLM_DIG': 'no label', 'TLM_SEAM': 'no label', 'DTM': 'no label', 'QLOOK': 'no label', 'METADATA': 'no label', 'GAZ': 'no label', 'THN_BUAT1': 'no label', 'SBR_DATA1': 'no label', 'METODE1': 'no label', 'TLM_SEAM1': 'no label', 'DTM1': 'no label', 'QLOOK1': 'no label', 'METADATA1': 'no label', 'GAZ1': 'no label', 'NAMA_PEK1': 'no label', 'PELAKSANA1': 'no label', 'THN_BUAT2': 'no label', 'SBR_DATA2': 'no label', 'METODE2': 'no label', 'TLM_SEAM2': 'no label', 'DTM2': 'no label', 'QLOOK2': 'no label', 'METADATA2': 'no label', 'GAZ2': 'no label', 'NAMA_PEK2': 'no label', 'PELAKSANA2': 'no label', 'THN_BUAT3': 'no label', 'SBR_DATA3': 'no label', 'METODE3': 'no label', 'TLM_SEAM3': 'no label', 'DTM3': 'no label', 'QLOOK3': 'no label', 'METADATA3': 'no label', 'GAZ3': 'no label', 'NAMA_PEK3': 'no label', 'PELAKSANA3': 'no label', 'THN_BUAT4': 'no label', 'SBR_DATA4': 'no label', 'METODE4': 'no label', 'TLM_SEAM4': 'no label', 'DTM4': 'no label', 'QLOOK4': 'no label', 'METADATA4': 'no label', 'GAZ4': 'no label', 'NAMA_PEK4': 'no label', 'PELAKSANA4': 'no label', 'THN_BUAT5': 'no label', 'SBR_DATA5': 'no label', 'METODE5': 'no label', 'TLM_SEAM5': 'no label', 'DTM5': 'no label', 'QLOOK5': 'no label', 'METADATA5': 'no label', 'GAZ5': 'no label', 'NAMA_PEK5': 'no label', 'PELAKSANA5': 'no label', 'THN_BUAT': 'no label', 'SBR_DATA': 'no label', 'METODE': 'no label', 'NAMA_PEK': 'no label', 'PELAKSANA': 'no label', 'THN_SEAM': 'no label', 'THN_DTM': 'no label', 'THN_QLOOK': 'no label', 'THN_META': 'no label', 'THN_GAZ': 'no label', 'KET': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', });
lyr_IndeksPetaRBISkala150K_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});